# identifiers for edge partitions
EDGE_PARTITION_EVENT = "Event"
EDGE_PARTITION_RE_SAMPLE = "Resample"
EDGE_PARTITION_TARGET_POSITION = "target_reposition"
EDGE_PARTITION_PARTICLE_STATE = "Particle_State"
EDGE_PARTITION_PARTICLE_TO_FILTER = "Particle_to_filter"
RETINA_X_SIZE = 304
RETINA_Y_SIZE = 240
RETINA_BASE_KEY = 0x00100000
RETINA_MASK = 0xFFF00000
FILTER_BASE_KEY = 0x01000000
FILTER_BASE_MASK = 0xFFFFFE00
RETINA_Y_BIT_SHIFT = 9
MAIN_PARTICLE_BASE_KEY = 0x01100000
