# identifiers for edge partitions
EDGE_PARTITION_EVENT = "Event"
EDGE_PARTITION_RE_SAMPLE = "Resample"
EDGE_PARTITION_TARGET_POSITION = "target_reposition"
EDGE_PARTITION_PARTICLE_STATE = "Particle_State"
RETINA_X_SIZE = 304
RETINA_Y_SIZE = 240